### ISSUE TITLE
npm package is still running v2.9 of chartjs

### ISSUE THREAD

**Issue by murageyun** [aomran/ember-cli-chart#204]
The [NPM package](https://www.npmjs.org/package/ember-cli-chart) still points to old version of chartjs (V2.9). The project is currently on v4.2.1 https://github.com/aomran/ember-cli-chart/blob/625a50f8a360ed72e8720a59e2a19c4d9b586833/package.json#L39

The dependencies were updated on GitHub without bumping the package version.

**Comment by murageyun** [comment]
closing this in favor of https://github.com/aomran/ember-cli-chart/issues/145

**Comment by lougreenwood** [comment]
Version 3.7.2 on npm is still providing version `2.9.4` of chart.js...

```
  ember-cli-chart@3.7.2:
    dependencies:
      chart.js: 2.9.4
      ember-cli-babel: 7.26.11
      ember-cli-htmlbars: 5.7.2
      ember-cli-node-assets: 0.2.2
      fastboot-transform: 0.1.3
    transitivePeerDependencies:
      - supports-color
 ```
