### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by jackmatt2** [aomran/ember-cli-chart#3]
Can you add legend to the component

``` javascript
import Ember from 'ember';
/* global Chart */

export default Ember.Component.extend({
  tagName: 'canvas',
  attributeBindings: ['width', 'height'],

  renderChart: function(){
    var context = this.get('element').getContext('2d');
    var data = this.get('data');
    var type = this.get('type').capitalize();
    var options = Ember.merge({}, this.get('options'));

    var chart = new Chart(context)[type](data, options);

    //************** LEGEND
    var legend = chart.generateLegend();
    this.$().parent().append(legend);
    //**************

    this.set('chart', chart);
  }.on('didInsertElement'),

  destroyChart: function(){
    this.get('chart').destroy();
  }.on('willDestroyElement'),

  updateChart: function(){
    this.destroyChart();
    this.renderChart();
  }.observes('data', 'options')
});
```

And the following css makes it look nice

``` css
*[class$='-legend'] {
  list-style: none;
  position: absolute;
  right: 8px;
  top: 0;
}
*[class$='-legend'] li {
  display: block;
  padding-left: 30px;
  position: relative;
  margin-bottom: 4px;
  border-radius: 5px;
  padding: 2px 8px 2px 28px;
  font-size: 14px;
  cursor: default;
  -webkit-transition: background-color 200ms ease-in-out;
  -moz-transition: background-color 200ms ease-in-out;
  -o-transition: background-color 200ms ease-in-out;
  transition: background-color 200ms ease-in-out;
}
*[class$='-legend'] li:hover {
  background-color: #fafafa;
}
*[class$='-legend'] li span {
  display: block;
  position: absolute;
  left: 0;
  top: 0;
  width: 20px;
  height: 100%;
  border-radius: 5px;
}
```
